export const mockedPerformanceCards = [
  {
    id: 1,
    title: "Effort",
    description:
      "Effort metrics help you understand how involved, and productive, the agency is with their brands on a daily basis.",
    details: [
      {
        id: 1,
        title: "Posts",
        description: "Daily average per brand",
        value: 829,
        status: "Verified",
        percentage: 10.1,
        graph: [
          {
            name: "Page A",
            uv: 4000,
            pv: 2400,
            amt: 2400,
          },
          {
            name: "Page B",
            uv: 3000,
            pv: 1398,
            amt: 2210,
          },
          {
            name: "Page C",
            uv: 2000,
            pv: 9800,
            amt: 2290,
          },
          {
            name: "Page D",
            uv: 2780,
            pv: 3908,
            amt: 2000,
          },
          {
            name: "Page E",
            uv: 1890,
            pv: 4800,
            amt: 2181,
          },
          {
            name: "Page F",
            uv: 2390,
            pv: 3800,
            amt: 2500,
          },
          {
            name: "Page G",
            uv: 3490,
            pv: 4300,
            amt: 2100,
          },
        ],
        performing: "Performing better than 75% of similar agencies",
      },
      {
        id: 2,
        title: "Interactions",
        description: "Daily average per brand",
        value: 1256,
        status: "Verified",
        percentage: 10.1,
        graph: [
          {
            name: "Page A",
            uv: 4000,
            pv: 2400,
            amt: 2400,
          },
          {
            name: "Page B",
            uv: 3000,
            pv: 1398,
            amt: 2210,
          },
          {
            name: "Page C",
            uv: 2000,
            pv: 9800,
            amt: 2290,
          },
          {
            name: "Page D",
            uv: 2780,
            pv: 3908,
            amt: 2000,
          },
          {
            name: "Page E",
            uv: 1890,
            pv: 4800,
            amt: 2181,
          },
          {
            name: "Page F",
            uv: 2390,
            pv: 3800,
            amt: 2500,
          },
          {
            name: "Page G",
            uv: 3490,
            pv: 4300,
            amt: 2100,
          },
        ],
        performing: "Performing better than 75% of similar agencies",
      },
    ],
  },
  {
    id: 2,
    title: "Effectiveness",
    description:
      "Effectiveness metrics help you understand the value you're getting for money you spend with this agency.",
    details: [
      {
        id: 1,
        title: "Engaged Posts",
        description: "Total number of posts that have received engagement",
        value: 829,
        status: "Verified",
        percentage: 10.1,
        graph: [
          {
            name: "Page A",
            uv: 4000,
            pv: 2400,
            amt: 2400,
          },
          {
            name: "Page B",
            uv: 3000,
            pv: 1398,
            amt: 2210,
          },
          {
            name: "Page C",
            uv: 2000,
            pv: 9800,
            amt: 2290,
          },
          {
            name: "Page D",
            uv: 2780,
            pv: 3908,
            amt: 2000,
          },
          {
            name: "Page E",
            uv: 1890,
            pv: 4800,
            amt: 2181,
          },
          {
            name: "Page F",
            uv: 2390,
            pv: 3800,
            amt: 2500,
          },
          {
            name: "Page G",
            uv: 3490,
            pv: 4300,
            amt: 2100,
          },
        ],
        performing: "Performing better than 72% of similar agencies",
      },
      {
        id: 2,
        title: "Avg. engagement per post",
        description: "The average amount of engagement a single post receives",
        value: 134,
        status: "Verified",
        percentage: -3.1,
        graph: [
          {
            name: "Page A",
            uv: 4000,
            pv: 2400,
            amt: 2400,
          },
          {
            name: "Page B",
            uv: 3000,
            pv: 1398,
            amt: 2210,
          },
          {
            name: "Page C",
            uv: 2000,
            pv: 9800,
            amt: 2290,
          },
          {
            name: "Page D",
            uv: 2780,
            pv: 3908,
            amt: 2000,
          },
          {
            name: "Page E",
            uv: 1890,
            pv: 4800,
            amt: 2181,
          },
          {
            name: "Page F",
            uv: 2390,
            pv: 3800,
            amt: 2500,
          },
          {
            name: "Page G",
            uv: 3490,
            pv: 4300,
            amt: 2100,
          },
        ],
        performing: "Performing better than 81% of similar agencies",
      },
      {
        id: 3,
        title: "Engagement rate",
        description: "Percentage of posts that result in engagement",
        value: "92.1%",
        status: "Verified",
        percentage: 5.2,
        graph: [
          {
            name: "Page A",
            uv: 4000,
            pv: 2400,
            amt: 2400,
          },
          {
            name: "Page B",
            uv: 3000,
            pv: 1398,
            amt: 2210,
          },
          {
            name: "Page C",
            uv: 2000,
            pv: 9800,
            amt: 2290,
          },
          {
            name: "Page D",
            uv: 2780,
            pv: 3908,
            amt: 2000,
          },
          {
            name: "Page E",
            uv: 1890,
            pv: 4800,
            amt: 2181,
          },
          {
            name: "Page F",
            uv: 2390,
            pv: 3800,
            amt: 2500,
          },
          {
            name: "Page G",
            uv: 3490,
            pv: 4300,
            amt: 2100,
          },
        ],
        performing: "Performing better than 92% of similar agencies",
      },
    ],
  },
];
