export const mockedPortfolioCards = [
  {
    id: 1,
    name: "Nurx",
    icon: "_mock_/portfolio/card-icon.svg",
    status: "Verified",
    local: { city: "San Francisco", country: "United States" },
    website: "https://www.nurx.com",
    industry: "Hospital & Health Care",
    business_size: "Large Business ($10M-$1B)",
    services: [
      "SOCIAL MEDIA MARKETING",
      "CONTENT MARKETING",
      "GRAPHIC DESIGN",
      "CREATIVE STRATEGY",
    ],
    description:
      "NURX PARTNERED WITH COMMANDO TO BETTER CONNECT WITH THE LGBTQ COMMUNITY IN PROMOTING PrEP, A ONCE DAILY HIV PREVENTION PILL.",
  },
  {
    id: 2,
    name: "Music City PrEP Clinic",
    icon: "_mock_/portfolio/card-icon.svg",
    status: "Verified",
    local: { city: "Nashville", country: "United States" },
    website: " https://www.musiccityprep.org",
    industry: "Hospital & Health Care",
    business_size: "Large Business ($10M-$1B)",
    services: [
      "SOCIAL MEDIA MARKETING",
      "SEARCH ENGINE OPTIMIZATION",
      "CONTENT MARKETING",
      "GRAPHIC DESIGN",
      "CREATIVE STRATEGY",
      "INFLUENCER MARKETING",
      "CONTENT MARKETING",
      "GRAPHIC DESIGN",
      "GROWTH STRATEGIES",
      "VIDEO PRODUCTION",
      "WEB DEVELOPMENT",
      "COPYWRITING",
      "CREATIVE STRATEGY",
    ],
    description:
      "COMMANDO provides advertising services targeting the LGBTQ community through a direct and exclusive network of publishers.",
  },
];
